### ISSUE TITLE
Cannot disable logging?

### ISSUE THREAD

**Issue by ruckus** [rubymotion-community/motion-http#2]
version = 1.0.0
platform: iOS 13.5.1

I am calling `HTTP.logger.disable!` but I am still seeing log output in the console when deployed to simulator or device.

I am also creating my own client like

```ruby
    @client = HTTP::Client.new(url)
```

so I can set custom headers. Perhaps the singleton `HTTP.logger` and the `@client` logger instance differ?

**Comment by andrewhavens** [comment]
Hi @ruckus 👋 Thanks for reporting this bug. I just pushed a fix for this. Can you try version 1.0.1 and let me know if that fixes it for you?

**Comment by ruckus** [comment]
Thanks @andrewhavens version `1.0.1` seems to be working.

I had noticed the issue in production because we have some large response payloads and the app was crashing trying to log that large amount of data.
